services:
  flask_app:
    container_name: flask_app
    image: flask_app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:docker@flask_db:5432/rik
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:latest
    environment:
      POSTGRES_DB: rik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}